# Site settings
title: dialytica
email: annawa.khoir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just kind of personal developer blog. Uh... whatever I hope you enjoy reading it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dialytica.github.io" # the base hostname & protocol for your site
twitter_username: nnawaa
github_username:  dialytica

# Build settings
markdown: kramdown
